### PR TITLE
Added bullet points to comparison section.

### PR DESCRIPTION
**Pull request by chrisgrace3**
@bontgoy Please review feature branch index.html file before I merge into master.

### CODE REVIEW

**Comment by Bontgoy** [comment]
Hi @chrisgrace3 

If you are tagging me on material that does not have an optional teacher tag please let me know what you would like me to look at.  Ask some questions and guide me through the PR.  Im happy to checkout your code and provided thoughtful replies.

Did you mean to close this pull request and not merge it by the way?

**Comment by chrisgrace3** [comment]
Hi Tyler,

I did this per an optional step in one of last week's assignments. The only
reason I merged is because I needed the assignment to be completed before
it was graded this week.

**Comment by Bontgoy** [comment]
@chrisgrace3 I am wondering because the log says that you only closed this PR and did not merge it.

Do you need to reopen this and merge it or did you do that on another PR?

**Comment by Bontgoy** [comment]
The file change here shows that your master remote does not have these changes yet.  If you want this file to have these changes you should definitely merge it here.

You can do that be reopening the pull request.

**Pull request closed without merging**
